import './globals.css'
import { Lora, Quicksand } from 'next/font/google'
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar";
import Head from 'next/head'

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lora',
  display: 'swap',
})

const inter = Inter({ subsets: ['latin'] })

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-quicksand',
  display: 'swap',
})

export const metadata = {
  title: 'Farm Manager',
  description: 'Generated by Aadi Sharma',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   return (
      <html lang="en">
        <body className="font-body bg-gray-900 text-white">
          <div className="container">
            <Navbar />
            <div className="content">{children}</div>
          </div>
        </body>
      </html>
  );
}