import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Farm Manager',
  description: 'Generated by Aadi Sharma',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <div className="container">
        <Navbar />
        <div className="content">{children}</div>
      </div>
      </body>
      </html>
  );
}
